config/routes.rb
Rails.application.routes.draw do
  resources :generator, only: [:index]
  resources :report, only: [:index]

  get 'cat_gen', to: "generator#category"
  get 'vsales_product', to: 'report#vsales_product'
  get 'vsales_product_choice', to: 'report#vsales_product_choice'
  get 'vsales_year', to: 'report#vsales_year'
  get 'vsales_loc', to: 'report#vsales_loc'
  get 'vsales_lochice', to: 'report#vsales_lochice'
  get 'posemail_gen', to:'generator#posemail'
  get 'vsales_gen', to:'generator#vsales'

  get 'vsaleschoice', to: 'report#vsaleschoice'

  get 'posemailchoice', to: 'report#posemailchoice'

  get 'generator/vsales'

  get 'signin', to: 'sessions#new'

  get 'vsales', to: 'report#vsales'
  get 'posemail', to: 'report#posemail'
  get 'signout', to: 'sessions#destroy'

  resources :tests
  resources :sessions, except:[:update, :edit]

  get 'welcome/index'

  root 'welcome#index'

end

app/controllers/report_controller.rb
class ReportController < ApplicationController
	before_action :not_signedin?

  def index
    
  end
  def vsales
    
  end

  def vsaleschoice
    @tanggal_awal =  params[:posemails][:startdate]
    @tanggal_akhir =  params[:posemails][:enddate]
    @end_date =  params[:posemails][:startdate]

    a = params[:posemails][:top10]
    
    cond = params[:posemails][:cond]
    
    if params[:posemails][:enddate].empty?
      @start_date = params[:posemails][:startdate]
    else
      @start_date = params[:posemails][:enddate]
    end
    
    @vsbp = Vsale.collection.aggregate([
        {"$match" => {"DateIssued" => {"$gte" => Time.parse(@end_date.to_s), "$lt" =>  Time.parse(@start_date.to_s)}}},
        { "$group" => {
            "_id" => "$Category",
            "totalPrice" => { "$sum" => "$#{cond}" },
            "totalOrdered" => { "$sum" => "$QtyOrdered" }
        }},
        { "$sort" => { "totalPrice" => -1 } },
        {"$limit" => a.to_i}
    ])

    @end_date = @end_date.to_date.strftime("%d %b %Y")
    @start_date = @start_date.to_date.strftime("%d %b %Y")
    cond
    @kondisi = ""
    cond.split("").each do |m| 
      if m == "C"
        @kondisi << " "
      end
      if m != "l" 
        @kondisi << m 
      else
       @kondisi << "l " 
      end 
    end

    render 'vsales'
  end

  def vsales_product
    
  end

  def vsales_product_choice
   
    a = params[:posemails][:top10]

    if params[:posemails][:category].empty?
      @kategori = nil
    else
      @kategori = params[:posemails][:category]
    end
    cond = params[:posemails][:cond]

    @start_date = params[:posemails][:startdate]
    @end_date = params[:posemails][:enddate]

    if params[:posemails][:startdate].empty? and params[:posemails][:enddate].empty?
      @start_date = Date.today.strftime("%Y/%m/%d")
      @end_date = @start_date
    end

    if @kategori.nil?
      @kategori = "ALL Category"
      @vsbp = Vsale.collection.aggregate([
        {"$match" => {"DateIssued" => {"$gte" => Time.parse(@start_date.to_s), "$lt" =>  Time.parse(@end_date.to_s)}}},
        { "$group" => {
            "_id" => "$ShortDesc",
            "totalUsed" => { "$sum" => "$#{cond}" },
            "totalOrdered" => { "$sum" => "$QtyOrdered" }
        }},
        { "$sort" => { "totalUsed" => -1 } },
        {"$limit" => a.to_i}
    ])
    else
      @vsbp = Vsale.collection.aggregate([
        {"$match" => {"Category" => "#{@kategori}", "DateIssued" => {"$gte" => Time.parse("#{@start_date}"), "$lt" =>  Time.parse("#{@end_date}")}}},
        { "$group" => {
            "_id" => "$ShortDesc",
            "totalUsed" => { "$sum" => "$TotalPrice" },
            "totalOrdered" => { "$sum" => "$QtyOrdered" }
        }},
        { "$sort" => { "totalUsed" => -1 } },
        {"$limit" => a.to_i}
    ])
    end    

    

    @end_date = @end_date.to_date.strftime("%d %b %Y")
    @start_date = @start_date.to_date.strftime("%d %b %Y")
    cond
    @kondisi = ""
    cond.split("").each do |m| 
      if m == "C"
        @kondisi << " "
      end
      if m != "l" 
        @kondisi << m 
      else
       @kondisi << "l " 
      end 
    end
    render 'vsales_product'
  end

  def vsales_year
    @month = Vsale.collection.aggregate(
        {"$project" => {
             "year" => {"$year" => "$DateIssued"}, 
             "month" => {"$month" => "$DateIssued"},
             "totalprice" => "$TotalPrice"
        }},
        {"$group" => {
             "_id" => {"year" => "$year", "month" => "$month"}, 
             "count" => {"$sum" => "$totalprice"}
        }}
    )
  end

  def vsales_loc
     
  end

  def vsales_lochice
    
    @tanggal_awal =  params[:posemails][:startdate]
    @tanggal_akhir =  params[:posemails][:enddate]
    @end_date =  params[:posemails][:startdate]
    a = params[:posemails][:top10]

    if params[:posemails][:enddate].empty?
      @start_date = params[:posemails][:startdate]
    else
      @start_date = params[:posemails][:enddate]
    end
    cond = params[:posemails][:cond]
    @vsbloc = Vsale.collection.aggregate([
        {"$match" => {"DateIssued" => {"$gte" => Time.parse(@end_date.to_s), "$lt" =>  Time.parse(@start_date.to_s)}}},
        { "$group" => {
            "_id" => "$OrgName",
            "totalPrice" => { "$sum" => "$#{cond}" }
        }},
        { "$sort" => { "totalPrice" => -1 } },
        {"$limit" => a.to_i}
    ])

    @end_date = @end_date.to_date.strftime("%d %b %Y")
    @start_date = @start_date.to_date.strftime("%d %b %Y")
    cond
    @kondisi = ""
    cond.split("").each do |m| 
      if m == "C"
        @kondisi << " "
      end
      if m != "l" 
        @kondisi << m 
      else
       @kondisi << "l " 
      end 
    end

    render 'vsales_loc'
  end

  def posemail
  	  	
  end

  def posemailchoice
    @orgnama = params[:posemails][:orgnama]
      
    if params[:posemails][:enddate].empty?
      @start_date = params[:posemails][:startdate]
      @end_date = @start_date
    else
      @start_date = params[:posemails][:enddate]
    end

    if params[:posemails][:startdate].empty?
      @end_date = params[:posemails][:enddate]
      @start_date = @end_date
    else
      @end_date = params[:posemails][:startdate]
    end
    
    if (@end_date.empty? and @start_date.empty?)
      @data = Posemail.all.no_timeout.group_by(&:Status)
    elsif @orgnama.empty?
       @data = Posemail.only(:AsalOrg, :DateReceived, :Processed, :Status).where({:DateReceivedTemp=> {:$gte=> "#{@end_date}T00:00:00.000Z".to_date, :$lt=> (("#{@start_date}T00:00:00.000Z".to_date)+1)}}).no_timeout.batch_size(1000000).group_by(&:Status) 
    else
      @data = Posemail.only(:AsalOrg, :DateReceived, :Processed, :Status).where(AsalOrg: @orgnama).where({:DateReceivedTemp=> {:$gte=> "#{@end_date}T00:00:00.000Z".to_date, :$lt=> (("#{@start_date}T00:00:00.000Z".to_date)+1)}}).no_timeout.batch_size(1000000).group_by(&:Status)
      @end_date = @end_date.to_date.strftime("%d %b %Y")
      @start_date = @start_date.to_date.strftime("%d %b %Y")
    end
    
    render 'posemail'
  end
end

app/helpers/report_helper.rb
module ReportHelper
end

app/views/report/index.html.erb
<div class="row">
	<h3 class="text-center">Report Menu</h3>
	<br>
	<div class="col-lg-12">
		<div class="col-lg-6">
			<div class="well text-center">
				<a href="/vsales_product">Sales by Product</a>
			</div>
			<div class="well text-center">
				<a href="/vsales">Sales by Category</a>
			</div>
		</div>
		<div class="col-lg-6">
			<div class="well text-center">
				<a href="/vsales_loc">Sales by Location</a>
			</div>
			<div class="well text-center">
				<a href="/vsales_year">Sales Years Summary</a>
			</div>
		</div>
	</div>
</div>

app/views/report/posemail.html.erb
<h2>
	Posemail Report
</h2>
<hr>
<%= form_for(:posemails, url: posemailchoice_path, html: {method: 'get'}) do |f| %>
 <label>* Org..</label> <%= f.select :orgnama, organisasi_choice, {include_blank: '---all---'} %>
 <label>* Start Date</label> <input id="datetimepicker1" name="posemails[startdate]" type="text" data-date-format="YYYY/MM/DD">
 <label>* End Date</label> <input id="datetimepicker2" name="posemails[enddate]" type="text" data-date-format="YYYY/MM/DD">
<%= f.submit 'search', class:"btn btn-primary btn-xs" %>
<% end %>
<hr>
<div class="well">
	<label>Nama Organisasi : </label> <%= @orgnama %><br>
	<label>Periode : </label> <%= @end_date %> - <%= @start_date %>
</div>

<table class="table table-responsive table-hover">
<thead>
	<tr>
		<th>Date</th>
		<th>Processed</th>
		<th>Not Processed</th>
		<th>Total</th>
	</tr>
</thead>
<tbody>
<% if @data.nil? or @data.count == 0 %>
	<tr>
		<td>Nothing to shown with the given data</td>
	</tr>
<% else %>
	<% @data.each do |k, mail| %>
	<tr style="background-color: grey; color: white;">
		<td><strong>Kategori : </strong><%= k %></td>
		<td></td>
		<td></td>
		<td></td>
	</tr>
	
		<% mail.group_by{|p| p["AsalOrg"]}.each do |org, maila| %>
			
				<tr style="background-color: yellow; ">
				<td>
					<strong>Org. : </strong><%= org %>
				</td>
				<td></td>
				<td></td>
				<td></td>
				</tr>
				<% maila.group_by{|k| k["DateReceived"]}.each do |x, l| %>
				<% taruhlah = l.select{|hash| hash["Processed"] == false }.length %>
				<tr style="<%= "background-color: red; color: white; font-style: bold;" if taruhlah > 0 %>">
					<td><%= x.to_date.strftime("%d %b %Y") %></td>
					<td><%= l.select{|hash| hash["Processed"] == true }.length %></td>
					<td><%= taruhlah %></td>
					<td><%= l.length %></td>
				</tr>
				<% end %>
			
		<% end %>
<% end %>	
<% end %>
</tbody>
</table>
 <script type="text/javascript">
            $(function () {
                $('#datetimepicker1').datetimepicker({
                	pickTime: false
                });
                 $('#datetimepicker2').datetimepicker({
                	pickTime: false
                });
            });
        </script>

app/views/report/vsales.html.erb
<h2>Top Sales by Category</h2>
<br>
<%= form_for(:posemails, url: vsaleschoice_path, html: {method: 'get'}) do |f| %>
 <label>* Based on :</label> <%= f.select :cond, [["Total Discount","TotalDiscount"],["Total Price","TotalPrice"],["Total Discount COGS","TotalDiscountCOGS"], ["Total Price COGS","TotalPriceCOGS"]] %>
 <label>* Start Date</label> <input id="datetimepicker1" name="posemails[startdate]" type="text" data-date-format="YYYY/MM/DD">
 <label>* End Date</label> <input id="datetimepicker2" name="posemails[enddate]" type="text" data-date-format="YYYY/MM/DD">
  <label>* Max. Row </label> <input id="top10" name="posemails[top10]" type="text" value="10">
<%= f.submit 'search', class:"btn btn-primary btn-xs" %>
<% end %>
<hr>
<% if @vsbp != nil %>
<% if !@vsbp.empty? %>
<script src="http://code.highcharts.com/highcharts.js"></script>
<script src="http://code.highcharts.com/modules/exporting.js"></script>
<div class="col-lg-12">
        <div id="container"></div>  
        <!-- <div id="container2" style="min-width: 310px; height: 400px; margin: 0 auto"></div>     -->
</div>
<script type="text/javascript">
    $(function () {
    $('#container').highcharts({
        chart: {
            zoomType: 'xy'
        },
        title: {
            text: 'Sales by Category'
        },
        subtitle: {
            text: 'Period: <%= "#{@end_date} - #{@start_date}" %> <br> Based on <%= @kondisi %> : <% @total2 = 0 %> <% @vsbp.each do |m, k, l| %><% @total2 += m["totalPrice"] %><% end %> <%= number_to_currency(@total2,unit: "Rp ", separator: ",", delimiter: ".") %>'
        },
        xAxis: [{
            categories: [<% @vsbp.each do |id, m| %> '<%= id["_id"] %>', <% end %>]
        }],
        yAxis: [{ // Primary yAxis
            labels: {
                format: 'Rp. {value}',
                style: {
                    color: Highcharts.getOptions().colors[1]
                }
            },
            title: {
                text: '<%= @cond %>',
                style: {
                    color: Highcharts.getOptions().colors[1]
                }
            },
            opposite: true

        }, { // Secondary yAxis
            gridLineWidth: 0,
            title: {
                text: 'Qty. Ordered',
                style: {
                    color: Highcharts.getOptions().colors[0]
                }
            },
            labels: {
                format: '{value} units',
                style: {
                    color: Highcharts.getOptions().colors[0]
                }
            }

        }],
        tooltip: {
            shared: true
        },
        legend: {
            layout: 'vertical',
            align: 'left',
            x: 120,
            verticalAlign: 'top',
            y: 80,
            floating: true,
            backgroundColor: (Highcharts.theme && Highcharts.theme.legendBackgroundColor) || '#FFFFFF'
        },
        series: [{
            name: 'Qty. Ordered',
            type: 'column',
            yAxis: 1,
            data: [<% @vsbp.each do |id, m| %> <%= id["totalOrdered"] %>, <% end %>],
            tooltip: {
                valueSuffix: ' units'
            }

        }, {
            name: '<%= @kondisi %>',
            type: 'spline',
            data: [<% @vsbp.each do |id, m| %> <%= id["totalPrice"] %>, <% end %>],
            tooltip: {
                valuePrefix: 'Rp. '
            }
        }]
    });
});


</script>

<% else %>
<div class="well">
   <label>Period : </label> <%= @end_date %> - <%= @start_date %>
</div>
Nothing to show with the given data
<% end %>
<% else %>
Please select Date Range first to show the data
<% end %>
<script>
 $(function () {
    $('#datetimepicker1').datetimepicker({
        pickTime: false
    });
        $('#datetimepicker2').datetimepicker({
        pickTime: false
    });
 });
</script>

app/views/report/vsales_loc.html.erb
<h2>Top Sales by Location</h2>
<br>
<%= form_for(:posemails, url: vsales_lochice_path, html: {method: 'get'}) do |f| %>
 <label>* Based on :</label> <%= f.select :cond, [["Total Discount","TotalDiscount"],["Total Price","TotalPrice"],["Total Discount COGS","TotalDiscountCOGS"], ["Total Price COGS","TotalPriceCOGS"]] %>  
 <label>* Start Date</label> <input id="datetimepicker1" name="posemails[startdate]" type="text" data-date-format="YYYY/MM/DD">
 <label>* End Date</label> <input id="datetimepicker2" name="posemails[enddate]" type="text" data-date-format="YYYY/MM/DD">
 <label>* Max. Row </label> <input id="top10" name="posemails[top10]" type="text" value="10">
<%= f.submit 'search', class:"btn btn-primary btn-xs" %>
<% end %>
<hr>
<% if @vsbloc != nil %>
<% if !@vsbloc.empty?%>
<script src="http://code.highcharts.com/highcharts.js"></script>
<script src="http://code.highcharts.com/modules/exporting.js"></script>
<div id="container5" style="min-width: 310px; height: 400px; margin: 0 auto"></div>
<script type="text/javascript">
$(function () {
    $('#container5').highcharts({
        chart: {
            type: 'column'
        },
        title: {
            text: 'Branch\'s Top Sales'
        },
        subtitle: {
            text: 'Period : <%= @end_date %> - <%= @start_date %> <br> Based on : <%= @kondisi %>'
        },
        xAxis: {
            type: 'category',
            labels: {
                rotation: -45,
                style: {
                    fontSize: '13px',
                    fontFamily: 'Verdana, sans-serif'
                }
            }
        },
        yAxis: {
            min: 0,
            title: {
                text: 'Rp (millions)'
            }
        },
        legend: {
            enabled: false
        },
        tooltip: {
            pointFormat: ' Value : <b>Rp. {point.y:.2f} millions</b>'
        },
        series: [{
            name: 'Population',
            data: [
                <% @vsbloc.each do |id, m| %>
                  ['<%= id["_id"] %>', <%= (id["totalPrice"]/1000000).round(2) %>],
                <% end %>
            ],
            dataLabels: {
                enabled: true,
                rotation: -90,
                color: '#FFFFFF',
                align: 'right',
                x: 4,
                y: 10,
                style: {
                    fontSize: '13px',
                    fontFamily: 'Verdana, sans-serif',
                    textShadow: '0 0 3px black'
                }
            }
        }]
    });
});
</script>
<% else %>
<div class="well">
   <label>Period : </label> <%= @end_date %> - <%= @start_date %>
</div>
Nothing to show with the given data
<% end %>
<% else %>
Please select Date Range first to show the data
<% end %>
<script>
 $(function () {
    $('#datetimepicker1').datetimepicker({
        pickTime: false
    });
        $('#datetimepicker2').datetimepicker({
        pickTime: false
    });
 });
</script>

app/views/report/vsales_product.html.erb
<h2>Top Sales by Product</h2>
<br>
<%= form_for(:posemails, url: vsales_product_choice_path, html: {method: 'get'}) do |f| %>
 <label>* Category</label> <%= f.select :category, kategori_choice, {include_blank: '---All Category---'} %>
 <label>* Based on :</label> <%= f.select :cond, [["Total Discount","TotalDiscount"],["Total Price","TotalPrice"],["Total Discount COGS","TotalDiscountCOGS"], ["Total Price COGS","TotalPriceCOGS"]] %><br><br>
 <label>* Start Date</label> <input id="datetimepicker1" name="posemails[startdate]" type="text" data-date-format="YYYY/MM/DD">
 <label>* End Date</label> <input id="datetimepicker2" name="posemails[enddate]" type="text" data-date-format="YYYY/MM/DD">
 <label>* Max. Row </label> <input id="top10" name="posemails[top10]" type="text" value="10">
<%= f.submit 'search', class:"btn btn-primary btn-xs" %>
<% end %>
<hr>
<% if @vsbp != nil %>
<% if !@vsbp.empty?%>
<script src="http://code.highcharts.com/highcharts.js"></script>
<script src="http://code.highcharts.com/modules/exporting.js"></script>

<div id="container" style="min-width: 310px; height: 400px; margin: 0 auto"></div>
<div id="container2" style="min-width: 310px; height: 400px; margin: 0 auto"></div>
<div id="container3" style="min-width: 310px; height: 400px; margin: 0 auto"></div>
<div class="col-lg-12">
</div>
<script type="text/javascript">
$(function () {
    $('#container').highcharts({
        chart: {
            zoomType: 'xy'
        },
        title: {
            text: 'Top Product'
        },
        subtitle: {
            text: 'Catgeory : <%= @kategori %> <br> Range <%= "#{@start_date} - #{@end_date}" %> <br> Total QTy. Out : <% @total2 = 0 %> <% @vsbp.each do |m, k, l| %><% @total2 += m["totalOrdered"] %><% end %> <%= @total2 %> & <%= "#{@cond} : " %> <% @total2 = 0 %> <% @vsbp.each do |m, k, l| %><% @total2 += m["totalUsed"] %><% end %> <%= number_to_currency(@total2,unit: "Rp ", separator: ",", delimiter: ".") %> <br> Based on : <%= @kondisi %>'
        },
        xAxis: [{
            categories: [ <% @vsbp.each do |m, k, l| %>
                            '<%= m["_id"] %>', 
                        <% end %>]
        }],
        yAxis: [{ // Primary yAxis
            labels: {
                format: '{value}',
                style: {
                    color: Highcharts.getOptions().colors[0]
                }
            },
            title: {
                text: 'Qty. Order (units)',
                style: {
                    color: Highcharts.getOptions().colors[0]
                }
            }
        }, { // Secondary yAxis
            title: {
                text: 'Value (Rp.)',
                style: {
                    color: Highcharts.getOptions().colors[1]
                }
            },
            labels: {
                format: '{value}',
                style: {
                    color: Highcharts.getOptions().colors[1]
                }
            },
            opposite: true
        }],
        tooltip: {
            shared: true
        },
        legend: {
            layout: 'vertical',
            align: 'left',
            x: 120,
            verticalAlign: 'top',
            y: 100,
            floating: true,
            backgroundColor: (Highcharts.theme && Highcharts.theme.legendBackgroundColor) || '#FFFFFF'
        },
        series: [
        {
            name: 'Quantity',
            type: 'column',
            yAxis: 1,
            data: [<% @vsbp.each do |m, k, l| %>
                    <%= m["totalOrdered"] %>,
                  <% end %>],
            tooltip: {
                valueSuffix: ' units'
            }

        }, {
            name: 'Value',
            type: 'spline',
            data: [<% @vsbp.each do |m, k, l| %>
                <%= m["totalUsed"] %>,
            <% end %>],
            tooltip: {
                valuePrefix: 'Rp. '
            }
        }]
    });
});


    $(function () {

    // Radialize the colors
    Highcharts.getOptions().colors = Highcharts.map(Highcharts.getOptions().colors, function (color) {
        return {
            radialGradient: { cx: 0.5, cy: 0.3, r: 0.7 },
            stops: [
                [0, color],
                [1, Highcharts.Color(color).brighten(-0.3).get('rgb')] // darken
            ]
        };
    });

    // Build the chart
    $('#container3').highcharts({
        chart: {
            plotBackgroundColor: null,
            plotBorderWidth: null,
            plotShadow: false
        },
        title: {
            text: 'Category Value Shared <br> <%= "#{@start_date} - #{@end_date}" %> <br> Total : <% @total2 = 0 %> <% @vsbp.each do |m, k, l| %><% @total2 += m["totalUsed"] %><% end %> <%= number_to_currency(@total2,unit: "Rp", separator: ",", delimiter: ".") %>'
        },
        tooltip: {
            pointFormat: '{series.name}: <b>{point.y:.f} </b>'
        },
        plotOptions: {
            pie: {
                allowPointSelect: true,
                cursor: 'pointer',
                dataLabels: {
                    enabled: true,
                    format: '<b>{point.name}</b>: {point.percentage:.1f} %',
                    style: {
                        color: (Highcharts.theme && Highcharts.theme.contrastTextColor) || 'black'
                    },
                    connectorColor: 'silver'
                }
            }
        },
        tooltip: {
            valueDecimals: 2,
            valuePrefix: 'Rp. ',
            valueSuffix: ' millions'
        },
        series: [{
            type: 'pie',
            name: 'Value ',
            data: [
               <% @vsbp.each do |m, k, l| %>
                ['<%= m["_id"] %>', <%= (m["totalUsed"]/1000000).round(2) %>],
            <% end %>
            ]
        }]
    });

 $('#container2').highcharts({
        chart: {
            plotBackgroundColor: null,
            plotBorderWidth: null,
            plotShadow: false
        },
        title: {
            text: 'Category Quantity Ordered <br> <%= "#{@start_date} - #{@end_date} - " %> <br>Total : <% @total2 = 0 %> <% @vsbp.each do |m, k, l| %><% @total2 += m["totalOrdered"] %><% end %> <%= @total2 %>'
        },
        tooltip: {
            pointFormat: '{series.name}: <b>{point.y:.f} </b>'
        },
        plotOptions: {
            pie: {
                allowPointSelect: true,
                cursor: 'pointer',
                dataLabels: {
                    enabled: true,
                    format: '<b>{point.name}</b>: {point.percentage:.1f} %',
                    style: {
                        color: (Highcharts.theme && Highcharts.theme.contrastTextColor) || 'black'
                    },
                    connectorColor: 'silver'
                }
            }
        },
        series: [{
            type: 'pie',
            name: 'Quantity Ordered',
            data: [
                 <% @vsbp.each do |m, k, l| %>
                ['<%= m["_id"] %>', <%= m["totalOrdered"] %>],
            <% end %>
            ]
        }]
    });
});

</script>
<% else %>
<div class="well">
   <label>Period : </label> <%= @start_date %> - <%= @end_date %>
</div>
Nothing to show with the given data
<%= @vsbp %>
<% end %>
<% else %>
Please select Date Range first to show the data
<% end %>
<script>
 $(function () {
    $('#datetimepicker1').datetimepicker({
        pickTime: false
    });
        $('#datetimepicker2').datetimepicker({
        pickTime: false
    });
 });
</script>

app/views/report/vsales_year.html.erb
<div class="col-lg-12">
        <!-- <div id="container"></div>  -->
        <div id="container4" style="min-width: 310px; height: 400px; margin: 0 auto"></div> 
</div>
<script type="text/javascript">
	$(function () {
    $('#container4').highcharts({
        chart: {
            type: 'spline'
        },
        title: {
            text: 'Transaction Summary 2012-2015'
        },
        subtitle: {
            text: 'per month'
        },
        xAxis: {
            type: 'datetime',
            dateTimeLabelFormats: { // don't display the dummy year
                month: '%b',
                year: '%b'
            },
            title: {
                text: 'Month'
            }
        },
        yAxis: {
            title: {
                text: 'Transaction'
            },
            min: 0
        },
        tooltip: {
            headerFormat: '<b>{series.name}</b><br>',
            pointFormat: '{point.x:%b}: Rp. {point.y:.f} millions'
        },

        series: [
        <% @month.group_by { |d| d['_id']['year'] }.sort_by{|year, records| year}.each do |k,g|  %>
       
        {
            name: '<%= k %>',
            // Define the data points. All series have a dummy year
            // of 1970/71 in order to be compared on the same x axis. Note
            // that in JavaScript, months start at 0 for January, 1 for February etc.
            data: [
                <% g.sort_by{|month, records| month["_id"]["month"]}.each do |n| %>
                    [Date.UTC(<%= k.to_i %>,  <%= n["_id"]["month"].to_i-1 %>), <%= (n["count"]/1000000).round(2) %>   ],
                <% end %>
            ]
        },
        <% end %>
        ]
    });
});
</script>
<script src="http://code.highcharts.com/highcharts.js"></script>
<script src="http://code.highcharts.com/modules/exporting.js"></script>